//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 11:33:08 AM CEST 
//


package org.example.schemabook;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.schemabook package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Libros_QNAME = new QName("http://www.example.org/SchemaBook", "Libros");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.schemabook
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Libro }
     * 
     */
    public Libro createLibro() {
        return new Libro();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Libro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/SchemaBook", name = "Libros")
    public JAXBElement<Libro> createLibros(Libro value) {
        return new JAXBElement<Libro>(_Libros_QNAME, Libro.class, null, value);
    }

}
