//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 11:33:08 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/SchemaBook", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.schemabook;
