//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 11:33:08 AM CEST 
//


package allen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Libro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Libro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Etiqueta", propOrder = {
    "id",
    "atlas-id",
	"ontology-id",
	"acronym",
	"name",
	"color-hex-triplet",
	"graph-order",
	"st-level",
	"hemisphere-id",
	"parent-structure-id",
	"children"
})
public class Etiqueta {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Atlas ID", required = true)
    protected String atlasid;
    @XmlElement(name = "acronym", required = true)
    protected String acronym;
    @XmlElement(name = "name", required = true)
    protected String name;
    @XmlElement(name = "Color Hex Triplet", required = true)
    protected String colorhextriplet;
    @XmlElement(name = "Graph Order", required = true)
    protected String GraphOrder;
    @XmlElement(name = "St. Level", required = true)
    protected String StLevel;
    @XmlElement(name = "Hemisphere ID", required = true)
    protected String HemisphereID;
    @XmlElement(name = "Parent Structure ID", required = true)
    protected String Parent;
    @XmlElement(name = "Children", required = true)
    protected String Children;
    @XmlElement(name = "OntologyID", required = true)
    protected String Ontology;

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }
    public String getAtlasID() {
        return atlasid;
    }
    public String getAcronym() {
        return acronym;
    }
    public String getName() {
        return name;
    }
    public String getCHT() {
        return colorhextriplet;
    }
    public String getGraphOrder() {
        return GraphOrder;
    }
    public String getStLevel() {
        return StLevel;
    }
    public String getHemisphere() {
        return HemisphereID;
    }
    public String getParent() {
        return Parent;
    }
    public String getChildren() {
        return Children;
    }
    public String getOntology() {
        return Ontology;
    }
}
